# Generated by Django 5.2.8 on 2025-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='direction',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='number_document',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tipe_sexo',
            field=models.CharField(null=True),
        ),
    ]
